name: Lunar Code Reviewer
description: Yet another AI powered code reviewer
author: 0xWelt

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

runs:
  using: node20
  main: dist/index.js
